title: "Nariman's Chemistry Notes"
email: 
description: >-
  A personal collection of chemistry notes, equations, and explanations by Nariman. 
  Built with Jekyll and the Minimal Mistakes theme.

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

twitter_username: 
github_username: narimansh1

search: true

markdown: kramdown
kramdown:
  math_engine: mathjax

paginate: 5
paginate_path: /page:num/
timezone: Asia/Singapore

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Nariman Shirinli"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Chemical Engineering student sharing curated chemistry notes."


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/narimansh1"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

nav:
  - title: "Home"
    url: /
  - title: "Physical Chemistry"
    url: /physical-chemistry/
  - title: "Analytical Chemistry"
    url: /analytical-chemistry/
  - title: "Python for Chemists"
    url: /python-for-chemistry/
